### ISSUE TITLE
Adding timeouts to the library

### ISSUE THREAD

**Issue by gpantazis** [jfjlaros/arduino-simple-rpc#21]
**Is your feature request related to a problem? Please describe.**
I have found myself needing timeouts on RPC calls to safeguard from spotty connections or otherwise be more responsive on the calling side to other tasks that are happening. I have need of it because I am using a Teensy3.2 to manage power (more involved than checking battery levels. There are multiple active systems) and control low-level peripherals. This is connected to a Tx2 serving real-time data. Since the uptime of serving the real time data is paramount I can't afford to be stalled by an RPC call.

This is a quality of life request that I imagine only affects people who have strict timing requirements on the calling side or need to be tolerant to faulty connections. 

**Describe the solution you'd like**
I believe a timeout feature can be "easily" enabled by modifying `serial.serial_for_url()` to include the keywords `timeout` and `write_timeout` which would be passed in as part of the `simple_rpc._Interface()` constructor. Note that `timeout = write_timeout = None` is the default and current behavior of `write()` and `read()` calls which are blocking. 

While both are easily enabled by adding them to the constructor, this is likely meaningless without additional modifications to the rest of the code

I am not 100% sure how that propagates throughout the rest of the code but I believe I have summarized a potential solution below.

A read timeout can produce incomplete data and the only way to know is to compare the received data with the requested (see pyserial/pyserial#18 and pyserial/pyserial#108), i.e:
```
b = serial.read_until(delimiter)
if b[-1] != terminator and self.timeout is not None:
    do something

OR Alternatively

b = serial.read(num_bytes)
if len(b) != num_bytes and self.timeout is not None:
    do something
```
I am guessing since `simple_rpc` has a defined protocol, with known lengths and delimiters, the two approaches above cover most scenarios I see in `io.py`. It would then be a matter of perhaps throwing some kind of exception (self defined or otherwise) that the user can catch and decide how to handle this. That said the current form of the (`io.py > _read_bytes_until()` and `io.py > until()`)  function would likely need to be re-thought due to the `while True`. Is a simple call to `serial.read_until(delimiter)` sufficient to replace them?

A write timeout is a different but perhaps simpler. In this instance a `serial.SerialTimeoutException` is raised which can be caught and re-raised as a builtin exception or handled in any other which way.

Note that this does unfortunately mean passing around a timeout flag everywhere, at least for the `read()` calls. The `write()` can always be wrapped in a `try except` block since it has minimal overhead and the timeout behavior is encoded in the `pyserial` object anyway.

Lastly there is the question of the initial connection after an `open()`. This can take longer than a defined timeout for any other call due to the exchange of more data. The two options I see here are either ignore the timeout for the open call (`self._connection.timeout = None`) and restore it once done, or allow a user to pass a `startup_timeout` value to the constructor.

**Describe alternatives you've considered**
An alternative that I will be implementing in the short run is a 2-thread solution:
```
thread-main: run general code and initiate request for RPC to thread-1
thread-1: listen for RPC request, launch thread-2 calling appropriate function and monitor runtime of thread.
                If runtime exceeds timeout, kill thread-2.
thread-2: run simple_rpc.call_method("method", param_list)
```

Regardless thank you for your time in reading this and hopefully it is useful

**Comment by jfjlaros** [comment]
That sounds like an interesting approach.

I can see how using packets and counters will make some form of error detection possible and by adding a header containing the intended receiver, it should be possible to create multiple communication channels. It would require having everything on the serial line using this protocol though because any plain stream (like a log) could contain a valid packet by chance.

Are you suggesting to use a separate control channel to send some sort of reset command after an error is detected?

Instead of a complete reimplementation, you might want to consider writing a plugin. As is, the library will work with anything that inherits from `Stream`.

**Comment by FourFUN** [comment]
Starting from the bottom first:
> Instead of a complete re-implementation, you might want to consider writing a plugin. As is, the library will work with anything that inherits from `Stream`.

This is so painfully obvious I am hitting my head on the wall for not thinking of it. I will try that eventually. For now, my team has changed the architecture in other parts of the host side code, so I will actually be adding the timeouts to the python library (as I mentioned in the OP) and if errors arise resolve them out of band (power cycle the Teensy).

**Read what follows at your own risk**

> I can see how using packets and counters will make some form of error detection possible and by adding a header containing the intended receiver, it should be possible to create multiple communication channels. It would require having everything on the serial line using this protocol though because any plain stream (like a log) could contain a valid packet by chance.

To answer the rest of your points, yeah the idea would be that everything going on the wire would need to be packetized. In this sense there would need to exist things like `simpleRPC_write()`, `simpleRPC_print()` or `simpleRPC_log()` for asynchronous logging from the board to the host. Under the hood these might be as simple as `Stream.write(simpleRPC_cobs_encode(data))` although the details are never that easy.

Regarding handling errors, I think the packetization limits the kinds of errors you can get. I think the categories are schema related, in which case the user must fix their code, or timing related in which case you must separate between host and board side.
On the board since you always blindly send things back so you don't have to handle many errors.

1. The first "error" is receiving an RPC with count < current count in which case just ignore it or if that is to complex execute it and let the host manage. 
2. The other error is hitting some kind of infinite/long loop or other exception of some kind and the host times-out. The responsibility here falls on the host side to retry the RPC again but eventually the board needs an out-of-band solution (Watchdog timer, external reset pin, etc). 
Only (1.) is a simpleRPC problem so I argue the board side just doesn't handle errors or does so silently.

On the host side, you can handle errors any way you want. A first approach for both types of errors is simply retrying up to a certain amount of times (user configurable?) and then throw an error the user must handle. 

That said the benefit of the packet header containing the `proc_id` and a `counter` is that if you do receive a reply that doesn't match what you just sent out, you can also warn, ignore, or cache and return if the new request is also delayed. For example what I am imagining is (sorry for the horrible diagram):
```
    HOST                                  BOARD
RPC(proc=0, count=0, args) ---------> proc_0(args) 
                     x--DELAYED<----- REPLY(proc=0, count=0) 
TIMEOUT
RPC(proc=0, count=1, args) ---------> proc_0(args) 
REPLY(proc=0, count=0)<---x
cache REPLY
if Timeout return REPLY and warn
REPLY(proc=0, count=1) <------------- REPLY(proc=0, count=1)
return REPLY
```
If I was going to implement something new right now, it would be probably be something along this version.

That said, instead of being delayed/lost you could imagine some kind of threading behavior on the board, such as on an ESP32. The return values on the host side are now more involved as you match returns with requests. For example you could for each `proc` maintain a `queue.PriorityQueue(size=255)` that orders by the `count`. Then, as results arrive you would `put()` them in the respective queue. The user can then retrieve all the results they want from them. In the radar world results usually also have a time of validity so you can filter out spurious values that way.

The python library in that sense could be "synchronous" and return just 1 result, or "asynchronous" and return any results as they arrive (synchronous and asynchronous here are not implying the `async` module, just the concept). 

At this point I know I am dreaming so I am going all the way and just throwing cool ideas out 😄. That said the basic packetization allowing two-way communication is probably tractable. I will eventually try a version using a class that inherits from `Stream`

Thank you so much for your insights and reading through my long messages. As always great library!

**Comment by jfjlaros** [comment]
You might want to have a look at this [serial multiplexer library](https://github.com/jfjlaros/serialMux) and the matching [host implementation](https://github.com/jfjlaros/arduino-serial-mux). It uses its own packet protocol to offer multiple virtual serial devices over the same physical line.

Perhaps this is a nice starting point for your idea?
